version: build{build}

branches:
  except:
    - project/travis

environment:
  matrix:
  - name: win32
    platform: amd64_x86
    qt: msvc2017

install:
  - pip.exe install conan
  - conan --version
  - python --version

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set GOPATH=c:\gopath
  - set QTDIR=C:\Qt\5.9.5\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;%GOPATH%\bin;
  - mkdir build
  - cd build
  - qmake ../tests/backpressureunittests/backpressureunittests.pro
  - tree /F /A
  - nmake
  - backpressure.exe
